config/routes.rb
Rails.application.routes.draw do

  get '/registrar', to: 'user#new'
  post '/registrar', to: 'user#create'

  get 'rooms/index'
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'
  resources :rooms do
    resources :messages
  end
  # resources :users
  root 'rooms#index'
  get 'clear_session', to: 'sessions#clear_session'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  belongs_to :room
  after_create_commit {broadcast_append_to self.room}
end

app/models/room.rb
class CreateRooms < ActiveRecord::Migration[6.1]
    def change
      create_table :rooms do |t|
      t.string :name
      t.timestamps
  
      end
    end
  end

  class Room < ApplicationRecord
    validates_uniqueness_of :name
    scope :public_rooms, -> { where(is_private: false) }
    after_create_commit {broadcast_append_to "rooms"}
    has_many :messages
  end

app/models/user.rb
class User < ApplicationRecord
    validates_uniqueness_of :username
    scope :all_except, ->(user) {where.not(id: user)}
    after_create_commit {broadcast_append_to "users"}
    has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

helper_method :current_user

def current_user
    if session[:user_id]
        @current_user = User.find(session[:user_id])
    end
end

def log_in(user)
    session[:user_id] = user.id
    @current_user = user
end

def logged_in?
    !current_user.nil?
end

def log_out
    session.delete(:user_id)
    @current_user = nil
end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

    def create
      @current_user = current_user
      @message = @current_user.messages.create(msg_params.merge(room_id: params[:room_id]))
    end

    private

        def msg_params
        params.require(:message).permit(:content, :image)
        end
  end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :require_login

  def index
    @current_user = current_user
    @room = Room.new
    redirect_to '/signin' unless @current_user
    @rooms = Room.public_rooms
    @users = User.all_except(@current_user)
  end

  def create
    @room = Room.create(name: params["room"] ["name"])
  end

  def show
    @current_user = current_user
    @single_room = Room.find(params[:id])
    @rooms = Room.public_rooms
    @users = User.all_except(@current_user)
    @message = Message.new
    @messages = @single_room.messages
    @room = Room.new
    render "index"
  end


  def require_login
    redirect_to root_path unless current_user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create
        user = User.find_by(username: params[:session][:username])
        if user
            log_in(user)
            redirect_to root_path
        else
            render 'new'
        end
    end

    def destroy
        log_out if logged_in?
        redirect_to root_path
    end

    def clear_session
        session[:user_id] = nil
        redirect_to root_path
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @users = User.new
  end

  def create

    @users = User.new(user_params)
    if @users.save
      redirect_to '/signin'
    else
      render 'new'
    end
  end

  def index
    @users = User.all
  end

  private
  def user_params
    params.require(:users).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_new_message_form.html.erb
<div class="form-group msg-form">
  <%= form_with(model: [@single_room, @message], remote: true, class: "d-flex", html: { multipart: true }) do |f| %>
    <%= f.text_field :content, id: 'chat-text', class: "form-control msg-content", autocomplete: 'off' %>
    <%= f.file_field :image, id: 'chat-image', class: "form-control msg-image" %>
    <%= f.submit "Enviar", data: { disable_with: false }, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/_new_room_form.html.erb
<%= form_with(model: @room, remote: true, class: "d-flex" ) do |f| %>
    <%= f.text_field :name, class: "form-control", autocomplete: 'off' %>
    <%= f.submit "Criar Sala", data: { disable_with: false }, class: "btn btn-secondary" %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <head>
      <style>
      <%= ".msg-#{current_user&.id}" %> {
      background-color: #858585e3  !important;
      padding: 10px;
      }
      <%= ".cont-#{current_user&.id}" %> {
      display: flex;
      justify-content: flex-end
      }
    </style>
    <title>Wavechat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload", media: 'all'%>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= yield %>
  </body>

</html>

app/views/messages/_message.html.erb
<div class="cont-<%= message.user.id %>">
  <div class="message-box msg-<%= message.user.id %> " >
    <h6 class="name"> <%= message.user.username %> </h6>
  <%= message.content %>
  <% if message.image.attached? %>
    <div class="message-image">
      <%= image_tag message.image, class: "message-image", alt: "Image" %>
    </div>
  <% end %>
  </div>

</div>

app/views/rooms/_room.html.erb
<div class="room">
  <%= link_to room.name, room_path(room), class: "btn btn-room" %>
</div>

app/views/rooms/_rooms.html.erb
<div id="rooms">
  <% if rooms.present? %>
    <% rooms.each do |room| %>
      <%= render partial: "rooms/room", locals: { room: room } %>
    <% end %>
  <% end %>
</div>

app/views/rooms/create.turbo_stream.erb
<%= turbo_stream.replace "rooms" do %>
    <%= render partial: "rooms/rooms", locals: { rooms: Room.all } %>
  <% end %>

app/views/rooms/index.html.erb
<div class="row">
    <div class="col-md-3">
        <h5> Bem-vindo, <%= @current_user.username %>! </h5>
        <h4> Salas </h4>
        <input type="hidden" id="user-id" value="<%= @current_user.id %>">
        <%= render partial: "layouts/new_room_form" %>
        <div>
            <%= turbo_stream_from "rooms" %>
            <div id="rooms">
                <% @rooms.each do |room| %>
                    <%= link_to room.name, room_path(room), class: "btn btn-room" %>
                <% end %>
            </div>
        </div>
    </div>

    <div class="col-md-9">
        <% if @single_room %>
            <h4 class="text-center"> <%= @single_room.name %> </h4>
            <input type="hidden" id="room-id" value="<%= @single_room.id %>">
            <%= turbo_stream_from @single_room %>
            <div id="messages-container">
                <div id="messages">
                    <%= render @messages %>
                </div>
            </div>
            <%= render partial: 'layouts/new_message_form' %>
        <% end %>
    </div>
</div>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/user/new.html.erb
<%= form_for (:users) do |f| %>
    <%= f.label :username, 'Digite seu nome' %>
    <%= f.text_field :username, autocomplete: 'off' %>
    <%= f.submit 'Registrar' %>
<% end %>

app/views/users/_user.html.erb
<div> <p><%= user.username %></p> </div>